### ISSUE TITLE
urllib3.exceptions.LocationParseError: Failed to parse

### ISSUE THREAD

**Issue by jeis4wpi** [harishkrupo/oauth2ms#14]
Hi All,

I really think my config is close but I get a parse error ?

```shell
oauth2ms 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/v2.0/.well-known/openid-configuration

During handling of the above exception, another exception occurred:

```

[OpenID](https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/v2.0/.well-known/openid-configuration)

results in:

```shell

{"token_endpoint":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/oauth2/v2.0/token","token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt","client_secret_basic"],"jwks_uri":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/discovery/v2.0/keys","response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["pairwise"],"id_token_signing_alg_values_supported":["RS256"],"response_types_supported":["code","id_token","code id_token","id_token token"],"scopes_supported":["openid","profile","email","offline_access"],"issuer":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/v2.0","request_uri_parameter_supported":false,"userinfo_endpoint":"https://graph.microsoft.com/oidc/userinfo","authorization_endpoint":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/oauth2/v2.0/authorize","device_authorization_endpoint":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/oauth2/v2.0/devicecode","http_logout_supported":true,"frontchannel_logout_supported":true,"end_session_endpoint":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/oauth2/v2.0/logout","claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","nonce","preferred_username","name","tid","ver","at_hash","c_hash","email"],"kerberos_endpoint":"https://login.microsoftonline.com/589c76f5-ca15-41f9-884b-55ec15a0672a/kerberos","tenant_region_scope":"NA","cloud_instance_name":"microsoftonline.com","cloud_graph_host_name":"graph.windows.net","msgraph_host":"graph.microsoft.com","rbac_url":"https://pas.windows.net"}

```

What am I doing wrong ?

Thank you very much for writing this code.

**Comment by jeis4wpi** [comment]
<img width="1052" alt="Screen Shot 2021-11-11 at 3 49 34 PM" src="https://user-images.githubusercontent.com/42679190/141367091-b6097999-23b4-42f1-8dec-25fac026c736.png">

I added some openid perms?  Does that make sense
